/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAbsensiDiriRouteImport } from './routes/_authenticated/absensi-diri'
import { Route as AuthenticatedAnggotaRouteImport } from './routes/_authenticated/anggota'
import { Route as AuthenticatedCatatPelanggaranRouteImport } from './routes/_authenticated/catat-pelanggaran'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInputKokurRouteImport } from './routes/_authenticated/input-kokur'
import { Route as AuthenticatedInputMutabaahRouteImport } from './routes/_authenticated/input-mutabaah'
import { Route as AuthenticatedInputNilaiRouteImport } from './routes/_authenticated/input-nilai'
import { Route as AuthenticatedInputNilaiTahfizRouteImport } from './routes/_authenticated/input-nilai-tahfiz'
import { Route as AuthenticatedJadwalPelajaranRouteImport } from './routes/_authenticated/jadwal-pelajaran'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedManajemenAsramaRouteImport } from './routes/_authenticated/manajemen-asrama'
import { Route as AuthenticatedManajemenHalaqohRouteImport } from './routes/_authenticated/manajemen-halaqoh'
import { Route as AuthenticatedManajemenKelasRouteImport } from './routes/_authenticated/manajemen-kelas'
import { Route as AuthenticatedManajemenMapelRouteImport } from './routes/_authenticated/manajemen-mapel'
import { Route as AuthenticatedMutabaahSayaRouteImport } from './routes/_authenticated/mutabaah-saya'
import { Route as AuthenticatedNilaiPelajaranRouteImport } from './routes/_authenticated/nilai-pelajaran'
import { Route as AuthenticatedNilaiTahfizSayaRouteImport } from './routes/_authenticated/nilai-tahfiz-saya'
import { Route as AuthenticatedPelanggaranSayaRouteImport } from './routes/_authenticated/pelanggaran-saya'
import { Route as AuthenticatedPengaturanSesiRouteImport } from './routes/_authenticated/pengaturan-sesi'
import { Route as AuthenticatedPerangkatAjarRouteImport } from './routes/_authenticated/perangkat-ajar'
import { Route as AuthenticatedPerizinanRouteImport } from './routes/_authenticated/perizinan'
import { Route as AuthenticatedPresensiInsidentalRouteImport } from './routes/_authenticated/presensi-insidental'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedRekapMutabaahRouteImport } from './routes/_authenticated/rekap-mutabaah'
import { Route as AuthenticatedRekapNilaiRouteImport } from './routes/_authenticated/rekap-nilai'
import { Route as AuthenticatedRekapPelanggaranRouteImport } from './routes/_authenticated/rekap-pelanggaran'
import { Route as AuthenticatedRekapPerangkatAjarRouteImport } from './routes/_authenticated/rekap-perangkat-ajar'
import { Route as AuthenticatedRekapPresensiRouteImport } from './routes/_authenticated/rekap-presensi'
import { Route as AuthenticatedRekapTahfizRouteImport } from './routes/_authenticated/rekap-tahfiz'
import { Route as AuthenticatedScanPresensiRouteImport } from './routes/_authenticated/scan-presensi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbsensiDiriRoute =
  AuthenticatedAbsensiDiriRouteImport.update({
    id: '/absensi-diri',
    path: '/absensi-diri',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggotaRoute = AuthenticatedAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatatPelanggaranRoute =
  AuthenticatedCatatPelanggaranRouteImport.update({
    id: '/catat-pelanggaran',
    path: '/catat-pelanggaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInputKokurRoute = AuthenticatedInputKokurRouteImport.update({
  id: '/input-kokur',
  path: '/input-kokur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInputMutabaahRoute =
  AuthenticatedInputMutabaahRouteImport.update({
    id: '/input-mutabaah',
    path: '/input-mutabaah',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInputNilaiRoute = AuthenticatedInputNilaiRouteImport.update({
  id: '/input-nilai',
  path: '/input-nilai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInputNilaiTahfizRoute =
  AuthenticatedInputNilaiTahfizRouteImport.update({
    id: '/input-nilai-tahfiz',
    path: '/input-nilai-tahfiz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJadwalPelajaranRoute =
  AuthenticatedJadwalPelajaranRouteImport.update({
    id: '/jadwal-pelajaran',
    path: '/jadwal-pelajaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManajemenAsramaRoute =
  AuthenticatedManajemenAsramaRouteImport.update({
    id: '/manajemen-asrama',
    path: '/manajemen-asrama',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManajemenHalaqohRoute =
  AuthenticatedManajemenHalaqohRouteImport.update({
    id: '/manajemen-halaqoh',
    path: '/manajemen-halaqoh',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManajemenKelasRoute =
  AuthenticatedManajemenKelasRouteImport.update({
    id: '/manajemen-kelas',
    path: '/manajemen-kelas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManajemenMapelRoute =
  AuthenticatedManajemenMapelRouteImport.update({
    id: '/manajemen-mapel',
    path: '/manajemen-mapel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMutabaahSayaRoute =
  AuthenticatedMutabaahSayaRouteImport.update({
    id: '/mutabaah-saya',
    path: '/mutabaah-saya',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNilaiPelajaranRoute =
  AuthenticatedNilaiPelajaranRouteImport.update({
    id: '/nilai-pelajaran',
    path: '/nilai-pelajaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNilaiTahfizSayaRoute =
  AuthenticatedNilaiTahfizSayaRouteImport.update({
    id: '/nilai-tahfiz-saya',
    path: '/nilai-tahfiz-saya',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPelanggaranSayaRoute =
  AuthenticatedPelanggaranSayaRouteImport.update({
    id: '/pelanggaran-saya',
    path: '/pelanggaran-saya',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengaturanSesiRoute =
  AuthenticatedPengaturanSesiRouteImport.update({
    id: '/pengaturan-sesi',
    path: '/pengaturan-sesi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerangkatAjarRoute =
  AuthenticatedPerangkatAjarRouteImport.update({
    id: '/perangkat-ajar',
    path: '/perangkat-ajar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerizinanRoute = AuthenticatedPerizinanRouteImport.update({
  id: '/perizinan',
  path: '/perizinan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresensiInsidentalRoute =
  AuthenticatedPresensiInsidentalRouteImport.update({
    id: '/presensi-insidental',
    path: '/presensi-insidental',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRekapMutabaahRoute =
  AuthenticatedRekapMutabaahRouteImport.update({
    id: '/rekap-mutabaah',
    path: '/rekap-mutabaah',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRekapNilaiRoute = AuthenticatedRekapNilaiRouteImport.update({
  id: '/rekap-nilai',
  path: '/rekap-nilai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRekapPelanggaranRoute =
  AuthenticatedRekapPelanggaranRouteImport.update({
    id: '/rekap-pelanggaran',
    path: '/rekap-pelanggaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRekapPerangkatAjarRoute =
  AuthenticatedRekapPerangkatAjarRouteImport.update({
    id: '/rekap-perangkat-ajar',
    path: '/rekap-perangkat-ajar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRekapPresensiRoute =
  AuthenticatedRekapPresensiRouteImport.update({
    id: '/rekap-presensi',
    path: '/rekap-presensi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRekapTahfizRoute =
  AuthenticatedRekapTahfizRouteImport.update({
    id: '/rekap-tahfiz',
    path: '/rekap-tahfiz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScanPresensiRoute =
  AuthenticatedScanPresensiRouteImport.update({
    id: '/scan-presensi',
    path: '/scan-presensi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absensi-diri': typeof AuthenticatedAbsensiDiriRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/catat-pelanggaran': typeof AuthenticatedCatatPelanggaranRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/input-kokur': typeof AuthenticatedInputKokurRoute
  '/input-mutabaah': typeof AuthenticatedInputMutabaahRoute
  '/input-nilai': typeof AuthenticatedInputNilaiRoute
  '/input-nilai-tahfiz': typeof AuthenticatedInputNilaiTahfizRoute
  '/jadwal-pelajaran': typeof AuthenticatedJadwalPelajaranRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/manajemen-asrama': typeof AuthenticatedManajemenAsramaRoute
  '/manajemen-halaqoh': typeof AuthenticatedManajemenHalaqohRoute
  '/manajemen-kelas': typeof AuthenticatedManajemenKelasRoute
  '/manajemen-mapel': typeof AuthenticatedManajemenMapelRoute
  '/mutabaah-saya': typeof AuthenticatedMutabaahSayaRoute
  '/nilai-pelajaran': typeof AuthenticatedNilaiPelajaranRoute
  '/nilai-tahfiz-saya': typeof AuthenticatedNilaiTahfizSayaRoute
  '/pelanggaran-saya': typeof AuthenticatedPelanggaranSayaRoute
  '/pengaturan-sesi': typeof AuthenticatedPengaturanSesiRoute
  '/perangkat-ajar': typeof AuthenticatedPerangkatAjarRoute
  '/perizinan': typeof AuthenticatedPerizinanRoute
  '/presensi-insidental': typeof AuthenticatedPresensiInsidentalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rekap-mutabaah': typeof AuthenticatedRekapMutabaahRoute
  '/rekap-nilai': typeof AuthenticatedRekapNilaiRoute
  '/rekap-pelanggaran': typeof AuthenticatedRekapPelanggaranRoute
  '/rekap-perangkat-ajar': typeof AuthenticatedRekapPerangkatAjarRoute
  '/rekap-presensi': typeof AuthenticatedRekapPresensiRoute
  '/rekap-tahfiz': typeof AuthenticatedRekapTahfizRoute
  '/scan-presensi': typeof AuthenticatedScanPresensiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absensi-diri': typeof AuthenticatedAbsensiDiriRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/catat-pelanggaran': typeof AuthenticatedCatatPelanggaranRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/input-kokur': typeof AuthenticatedInputKokurRoute
  '/input-mutabaah': typeof AuthenticatedInputMutabaahRoute
  '/input-nilai': typeof AuthenticatedInputNilaiRoute
  '/input-nilai-tahfiz': typeof AuthenticatedInputNilaiTahfizRoute
  '/jadwal-pelajaran': typeof AuthenticatedJadwalPelajaranRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/manajemen-asrama': typeof AuthenticatedManajemenAsramaRoute
  '/manajemen-halaqoh': typeof AuthenticatedManajemenHalaqohRoute
  '/manajemen-kelas': typeof AuthenticatedManajemenKelasRoute
  '/manajemen-mapel': typeof AuthenticatedManajemenMapelRoute
  '/mutabaah-saya': typeof AuthenticatedMutabaahSayaRoute
  '/nilai-pelajaran': typeof AuthenticatedNilaiPelajaranRoute
  '/nilai-tahfiz-saya': typeof AuthenticatedNilaiTahfizSayaRoute
  '/pelanggaran-saya': typeof AuthenticatedPelanggaranSayaRoute
  '/pengaturan-sesi': typeof AuthenticatedPengaturanSesiRoute
  '/perangkat-ajar': typeof AuthenticatedPerangkatAjarRoute
  '/perizinan': typeof AuthenticatedPerizinanRoute
  '/presensi-insidental': typeof AuthenticatedPresensiInsidentalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rekap-mutabaah': typeof AuthenticatedRekapMutabaahRoute
  '/rekap-nilai': typeof AuthenticatedRekapNilaiRoute
  '/rekap-pelanggaran': typeof AuthenticatedRekapPelanggaranRoute
  '/rekap-perangkat-ajar': typeof AuthenticatedRekapPerangkatAjarRoute
  '/rekap-presensi': typeof AuthenticatedRekapPresensiRoute
  '/rekap-tahfiz': typeof AuthenticatedRekapTahfizRoute
  '/scan-presensi': typeof AuthenticatedScanPresensiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/absensi-diri': typeof AuthenticatedAbsensiDiriRoute
  '/_authenticated/anggota': typeof AuthenticatedAnggotaRoute
  '/_authenticated/catat-pelanggaran': typeof AuthenticatedCatatPelanggaranRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/input-kokur': typeof AuthenticatedInputKokurRoute
  '/_authenticated/input-mutabaah': typeof AuthenticatedInputMutabaahRoute
  '/_authenticated/input-nilai': typeof AuthenticatedInputNilaiRoute
  '/_authenticated/input-nilai-tahfiz': typeof AuthenticatedInputNilaiTahfizRoute
  '/_authenticated/jadwal-pelajaran': typeof AuthenticatedJadwalPelajaranRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/manajemen-asrama': typeof AuthenticatedManajemenAsramaRoute
  '/_authenticated/manajemen-halaqoh': typeof AuthenticatedManajemenHalaqohRoute
  '/_authenticated/manajemen-kelas': typeof AuthenticatedManajemenKelasRoute
  '/_authenticated/manajemen-mapel': typeof AuthenticatedManajemenMapelRoute
  '/_authenticated/mutabaah-saya': typeof AuthenticatedMutabaahSayaRoute
  '/_authenticated/nilai-pelajaran': typeof AuthenticatedNilaiPelajaranRoute
  '/_authenticated/nilai-tahfiz-saya': typeof AuthenticatedNilaiTahfizSayaRoute
  '/_authenticated/pelanggaran-saya': typeof AuthenticatedPelanggaranSayaRoute
  '/_authenticated/pengaturan-sesi': typeof AuthenticatedPengaturanSesiRoute
  '/_authenticated/perangkat-ajar': typeof AuthenticatedPerangkatAjarRoute
  '/_authenticated/perizinan': typeof AuthenticatedPerizinanRoute
  '/_authenticated/presensi-insidental': typeof AuthenticatedPresensiInsidentalRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rekap-mutabaah': typeof AuthenticatedRekapMutabaahRoute
  '/_authenticated/rekap-nilai': typeof AuthenticatedRekapNilaiRoute
  '/_authenticated/rekap-pelanggaran': typeof AuthenticatedRekapPelanggaranRoute
  '/_authenticated/rekap-perangkat-ajar': typeof AuthenticatedRekapPerangkatAjarRoute
  '/_authenticated/rekap-presensi': typeof AuthenticatedRekapPresensiRoute
  '/_authenticated/rekap-tahfiz': typeof AuthenticatedRekapTahfizRoute
  '/_authenticated/scan-presensi': typeof AuthenticatedScanPresensiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absensi-diri'
    | '/anggota'
    | '/catat-pelanggaran'
    | '/dashboard'
    | '/input-kokur'
    | '/input-mutabaah'
    | '/input-nilai'
    | '/input-nilai-tahfiz'
    | '/jadwal-pelajaran'
    | '/kalender'
    | '/manajemen-asrama'
    | '/manajemen-halaqoh'
    | '/manajemen-kelas'
    | '/manajemen-mapel'
    | '/mutabaah-saya'
    | '/nilai-pelajaran'
    | '/nilai-tahfiz-saya'
    | '/pelanggaran-saya'
    | '/pengaturan-sesi'
    | '/perangkat-ajar'
    | '/perizinan'
    | '/presensi-insidental'
    | '/profil'
    | '/rekap-mutabaah'
    | '/rekap-nilai'
    | '/rekap-pelanggaran'
    | '/rekap-perangkat-ajar'
    | '/rekap-presensi'
    | '/rekap-tahfiz'
    | '/scan-presensi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absensi-diri'
    | '/anggota'
    | '/catat-pelanggaran'
    | '/dashboard'
    | '/input-kokur'
    | '/input-mutabaah'
    | '/input-nilai'
    | '/input-nilai-tahfiz'
    | '/jadwal-pelajaran'
    | '/kalender'
    | '/manajemen-asrama'
    | '/manajemen-halaqoh'
    | '/manajemen-kelas'
    | '/manajemen-mapel'
    | '/mutabaah-saya'
    | '/nilai-pelajaran'
    | '/nilai-tahfiz-saya'
    | '/pelanggaran-saya'
    | '/pengaturan-sesi'
    | '/perangkat-ajar'
    | '/perizinan'
    | '/presensi-insidental'
    | '/profil'
    | '/rekap-mutabaah'
    | '/rekap-nilai'
    | '/rekap-pelanggaran'
    | '/rekap-perangkat-ajar'
    | '/rekap-presensi'
    | '/rekap-tahfiz'
    | '/scan-presensi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/absensi-diri'
    | '/_authenticated/anggota'
    | '/_authenticated/catat-pelanggaran'
    | '/_authenticated/dashboard'
    | '/_authenticated/input-kokur'
    | '/_authenticated/input-mutabaah'
    | '/_authenticated/input-nilai'
    | '/_authenticated/input-nilai-tahfiz'
    | '/_authenticated/jadwal-pelajaran'
    | '/_authenticated/kalender'
    | '/_authenticated/manajemen-asrama'
    | '/_authenticated/manajemen-halaqoh'
    | '/_authenticated/manajemen-kelas'
    | '/_authenticated/manajemen-mapel'
    | '/_authenticated/mutabaah-saya'
    | '/_authenticated/nilai-pelajaran'
    | '/_authenticated/nilai-tahfiz-saya'
    | '/_authenticated/pelanggaran-saya'
    | '/_authenticated/pengaturan-sesi'
    | '/_authenticated/perangkat-ajar'
    | '/_authenticated/perizinan'
    | '/_authenticated/presensi-insidental'
    | '/_authenticated/profil'
    | '/_authenticated/rekap-mutabaah'
    | '/_authenticated/rekap-nilai'
    | '/_authenticated/rekap-pelanggaran'
    | '/_authenticated/rekap-perangkat-ajar'
    | '/_authenticated/rekap-presensi'
    | '/_authenticated/rekap-tahfiz'
    | '/_authenticated/scan-presensi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/absensi-diri': {
      id: '/_authenticated/absensi-diri'
      path: '/absensi-diri'
      fullPath: '/absensi-diri'
      preLoaderRoute: typeof AuthenticatedAbsensiDiriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggota': {
      id: '/_authenticated/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AuthenticatedAnggotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catat-pelanggaran': {
      id: '/_authenticated/catat-pelanggaran'
      path: '/catat-pelanggaran'
      fullPath: '/catat-pelanggaran'
      preLoaderRoute: typeof AuthenticatedCatatPelanggaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/input-kokur': {
      id: '/_authenticated/input-kokur'
      path: '/input-kokur'
      fullPath: '/input-kokur'
      preLoaderRoute: typeof AuthenticatedInputKokurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/input-mutabaah': {
      id: '/_authenticated/input-mutabaah'
      path: '/input-mutabaah'
      fullPath: '/input-mutabaah'
      preLoaderRoute: typeof AuthenticatedInputMutabaahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/input-nilai': {
      id: '/_authenticated/input-nilai'
      path: '/input-nilai'
      fullPath: '/input-nilai'
      preLoaderRoute: typeof AuthenticatedInputNilaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/input-nilai-tahfiz': {
      id: '/_authenticated/input-nilai-tahfiz'
      path: '/input-nilai-tahfiz'
      fullPath: '/input-nilai-tahfiz'
      preLoaderRoute: typeof AuthenticatedInputNilaiTahfizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jadwal-pelajaran': {
      id: '/_authenticated/jadwal-pelajaran'
      path: '/jadwal-pelajaran'
      fullPath: '/jadwal-pelajaran'
      preLoaderRoute: typeof AuthenticatedJadwalPelajaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manajemen-asrama': {
      id: '/_authenticated/manajemen-asrama'
      path: '/manajemen-asrama'
      fullPath: '/manajemen-asrama'
      preLoaderRoute: typeof AuthenticatedManajemenAsramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manajemen-halaqoh': {
      id: '/_authenticated/manajemen-halaqoh'
      path: '/manajemen-halaqoh'
      fullPath: '/manajemen-halaqoh'
      preLoaderRoute: typeof AuthenticatedManajemenHalaqohRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manajemen-kelas': {
      id: '/_authenticated/manajemen-kelas'
      path: '/manajemen-kelas'
      fullPath: '/manajemen-kelas'
      preLoaderRoute: typeof AuthenticatedManajemenKelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manajemen-mapel': {
      id: '/_authenticated/manajemen-mapel'
      path: '/manajemen-mapel'
      fullPath: '/manajemen-mapel'
      preLoaderRoute: typeof AuthenticatedManajemenMapelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mutabaah-saya': {
      id: '/_authenticated/mutabaah-saya'
      path: '/mutabaah-saya'
      fullPath: '/mutabaah-saya'
      preLoaderRoute: typeof AuthenticatedMutabaahSayaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nilai-pelajaran': {
      id: '/_authenticated/nilai-pelajaran'
      path: '/nilai-pelajaran'
      fullPath: '/nilai-pelajaran'
      preLoaderRoute: typeof AuthenticatedNilaiPelajaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nilai-tahfiz-saya': {
      id: '/_authenticated/nilai-tahfiz-saya'
      path: '/nilai-tahfiz-saya'
      fullPath: '/nilai-tahfiz-saya'
      preLoaderRoute: typeof AuthenticatedNilaiTahfizSayaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggaran-saya': {
      id: '/_authenticated/pelanggaran-saya'
      path: '/pelanggaran-saya'
      fullPath: '/pelanggaran-saya'
      preLoaderRoute: typeof AuthenticatedPelanggaranSayaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan-sesi': {
      id: '/_authenticated/pengaturan-sesi'
      path: '/pengaturan-sesi'
      fullPath: '/pengaturan-sesi'
      preLoaderRoute: typeof AuthenticatedPengaturanSesiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perangkat-ajar': {
      id: '/_authenticated/perangkat-ajar'
      path: '/perangkat-ajar'
      fullPath: '/perangkat-ajar'
      preLoaderRoute: typeof AuthenticatedPerangkatAjarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perizinan': {
      id: '/_authenticated/perizinan'
      path: '/perizinan'
      fullPath: '/perizinan'
      preLoaderRoute: typeof AuthenticatedPerizinanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presensi-insidental': {
      id: '/_authenticated/presensi-insidental'
      path: '/presensi-insidental'
      fullPath: '/presensi-insidental'
      preLoaderRoute: typeof AuthenticatedPresensiInsidentalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap-mutabaah': {
      id: '/_authenticated/rekap-mutabaah'
      path: '/rekap-mutabaah'
      fullPath: '/rekap-mutabaah'
      preLoaderRoute: typeof AuthenticatedRekapMutabaahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap-nilai': {
      id: '/_authenticated/rekap-nilai'
      path: '/rekap-nilai'
      fullPath: '/rekap-nilai'
      preLoaderRoute: typeof AuthenticatedRekapNilaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap-pelanggaran': {
      id: '/_authenticated/rekap-pelanggaran'
      path: '/rekap-pelanggaran'
      fullPath: '/rekap-pelanggaran'
      preLoaderRoute: typeof AuthenticatedRekapPelanggaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap-perangkat-ajar': {
      id: '/_authenticated/rekap-perangkat-ajar'
      path: '/rekap-perangkat-ajar'
      fullPath: '/rekap-perangkat-ajar'
      preLoaderRoute: typeof AuthenticatedRekapPerangkatAjarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap-presensi': {
      id: '/_authenticated/rekap-presensi'
      path: '/rekap-presensi'
      fullPath: '/rekap-presensi'
      preLoaderRoute: typeof AuthenticatedRekapPresensiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap-tahfiz': {
      id: '/_authenticated/rekap-tahfiz'
      path: '/rekap-tahfiz'
      fullPath: '/rekap-tahfiz'
      preLoaderRoute: typeof AuthenticatedRekapTahfizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan-presensi': {
      id: '/_authenticated/scan-presensi'
      path: '/scan-presensi'
      fullPath: '/scan-presensi'
      preLoaderRoute: typeof AuthenticatedScanPresensiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbsensiDiriRoute: typeof AuthenticatedAbsensiDiriRoute
  AuthenticatedAnggotaRoute: typeof AuthenticatedAnggotaRoute
  AuthenticatedCatatPelanggaranRoute: typeof AuthenticatedCatatPelanggaranRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInputKokurRoute: typeof AuthenticatedInputKokurRoute
  AuthenticatedInputMutabaahRoute: typeof AuthenticatedInputMutabaahRoute
  AuthenticatedInputNilaiRoute: typeof AuthenticatedInputNilaiRoute
  AuthenticatedInputNilaiTahfizRoute: typeof AuthenticatedInputNilaiTahfizRoute
  AuthenticatedJadwalPelajaranRoute: typeof AuthenticatedJadwalPelajaranRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedManajemenAsramaRoute: typeof AuthenticatedManajemenAsramaRoute
  AuthenticatedManajemenHalaqohRoute: typeof AuthenticatedManajemenHalaqohRoute
  AuthenticatedManajemenKelasRoute: typeof AuthenticatedManajemenKelasRoute
  AuthenticatedManajemenMapelRoute: typeof AuthenticatedManajemenMapelRoute
  AuthenticatedMutabaahSayaRoute: typeof AuthenticatedMutabaahSayaRoute
  AuthenticatedNilaiPelajaranRoute: typeof AuthenticatedNilaiPelajaranRoute
  AuthenticatedNilaiTahfizSayaRoute: typeof AuthenticatedNilaiTahfizSayaRoute
  AuthenticatedPelanggaranSayaRoute: typeof AuthenticatedPelanggaranSayaRoute
  AuthenticatedPengaturanSesiRoute: typeof AuthenticatedPengaturanSesiRoute
  AuthenticatedPerangkatAjarRoute: typeof AuthenticatedPerangkatAjarRoute
  AuthenticatedPerizinanRoute: typeof AuthenticatedPerizinanRoute
  AuthenticatedPresensiInsidentalRoute: typeof AuthenticatedPresensiInsidentalRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRekapMutabaahRoute: typeof AuthenticatedRekapMutabaahRoute
  AuthenticatedRekapNilaiRoute: typeof AuthenticatedRekapNilaiRoute
  AuthenticatedRekapPelanggaranRoute: typeof AuthenticatedRekapPelanggaranRoute
  AuthenticatedRekapPerangkatAjarRoute: typeof AuthenticatedRekapPerangkatAjarRoute
  AuthenticatedRekapPresensiRoute: typeof AuthenticatedRekapPresensiRoute
  AuthenticatedRekapTahfizRoute: typeof AuthenticatedRekapTahfizRoute
  AuthenticatedScanPresensiRoute: typeof AuthenticatedScanPresensiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbsensiDiriRoute: AuthenticatedAbsensiDiriRoute,
  AuthenticatedAnggotaRoute: AuthenticatedAnggotaRoute,
  AuthenticatedCatatPelanggaranRoute: AuthenticatedCatatPelanggaranRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInputKokurRoute: AuthenticatedInputKokurRoute,
  AuthenticatedInputMutabaahRoute: AuthenticatedInputMutabaahRoute,
  AuthenticatedInputNilaiRoute: AuthenticatedInputNilaiRoute,
  AuthenticatedInputNilaiTahfizRoute: AuthenticatedInputNilaiTahfizRoute,
  AuthenticatedJadwalPelajaranRoute: AuthenticatedJadwalPelajaranRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedManajemenAsramaRoute: AuthenticatedManajemenAsramaRoute,
  AuthenticatedManajemenHalaqohRoute: AuthenticatedManajemenHalaqohRoute,
  AuthenticatedManajemenKelasRoute: AuthenticatedManajemenKelasRoute,
  AuthenticatedManajemenMapelRoute: AuthenticatedManajemenMapelRoute,
  AuthenticatedMutabaahSayaRoute: AuthenticatedMutabaahSayaRoute,
  AuthenticatedNilaiPelajaranRoute: AuthenticatedNilaiPelajaranRoute,
  AuthenticatedNilaiTahfizSayaRoute: AuthenticatedNilaiTahfizSayaRoute,
  AuthenticatedPelanggaranSayaRoute: AuthenticatedPelanggaranSayaRoute,
  AuthenticatedPengaturanSesiRoute: AuthenticatedPengaturanSesiRoute,
  AuthenticatedPerangkatAjarRoute: AuthenticatedPerangkatAjarRoute,
  AuthenticatedPerizinanRoute: AuthenticatedPerizinanRoute,
  AuthenticatedPresensiInsidentalRoute: AuthenticatedPresensiInsidentalRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRekapMutabaahRoute: AuthenticatedRekapMutabaahRoute,
  AuthenticatedRekapNilaiRoute: AuthenticatedRekapNilaiRoute,
  AuthenticatedRekapPelanggaranRoute: AuthenticatedRekapPelanggaranRoute,
  AuthenticatedRekapPerangkatAjarRoute: AuthenticatedRekapPerangkatAjarRoute,
  AuthenticatedRekapPresensiRoute: AuthenticatedRekapPresensiRoute,
  AuthenticatedRekapTahfizRoute: AuthenticatedRekapTahfizRoute,
  AuthenticatedScanPresensiRoute: AuthenticatedScanPresensiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
