/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAbsensiDiriRouteImport } from './routes/_authenticated/absensi-diri'
import { Route as AuthenticatedAnggotaRouteImport } from './routes/_authenticated/anggota'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedKesiswaanRouteImport } from './routes/_authenticated/kesiswaan'
import { Route as AuthenticatedManajemenAsramaRouteImport } from './routes/_authenticated/manajemen-asrama'
import { Route as AuthenticatedManajemenHalaqohRouteImport } from './routes/_authenticated/manajemen-halaqoh'
import { Route as AuthenticatedManajemenKelasRouteImport } from './routes/_authenticated/manajemen-kelas'
import { Route as AuthenticatedMutabaahSayaRouteImport } from './routes/_authenticated/mutabaah-saya'
import { Route as AuthenticatedPelanggaranSayaRouteImport } from './routes/_authenticated/pelanggaran-saya'
import { Route as AuthenticatedPengaturanSesiRouteImport } from './routes/_authenticated/pengaturan-sesi'
import { Route as AuthenticatedPresensiInsidentalRouteImport } from './routes/_authenticated/presensi-insidental'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedRekapPresensiRouteImport } from './routes/_authenticated/rekap-presensi'
import { Route as AuthenticatedScanPresensiRouteImport } from './routes/_authenticated/scan-presensi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbsensiDiriRoute =
  AuthenticatedAbsensiDiriRouteImport.update({
    id: '/absensi-diri',
    path: '/absensi-diri',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggotaRoute = AuthenticatedAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKesiswaanRoute = AuthenticatedKesiswaanRouteImport.update({
  id: '/kesiswaan',
  path: '/kesiswaan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManajemenAsramaRoute =
  AuthenticatedManajemenAsramaRouteImport.update({
    id: '/manajemen-asrama',
    path: '/manajemen-asrama',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManajemenHalaqohRoute =
  AuthenticatedManajemenHalaqohRouteImport.update({
    id: '/manajemen-halaqoh',
    path: '/manajemen-halaqoh',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManajemenKelasRoute =
  AuthenticatedManajemenKelasRouteImport.update({
    id: '/manajemen-kelas',
    path: '/manajemen-kelas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMutabaahSayaRoute =
  AuthenticatedMutabaahSayaRouteImport.update({
    id: '/mutabaah-saya',
    path: '/mutabaah-saya',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPelanggaranSayaRoute =
  AuthenticatedPelanggaranSayaRouteImport.update({
    id: '/pelanggaran-saya',
    path: '/pelanggaran-saya',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengaturanSesiRoute =
  AuthenticatedPengaturanSesiRouteImport.update({
    id: '/pengaturan-sesi',
    path: '/pengaturan-sesi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresensiInsidentalRoute =
  AuthenticatedPresensiInsidentalRouteImport.update({
    id: '/presensi-insidental',
    path: '/presensi-insidental',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRekapPresensiRoute =
  AuthenticatedRekapPresensiRouteImport.update({
    id: '/rekap-presensi',
    path: '/rekap-presensi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScanPresensiRoute =
  AuthenticatedScanPresensiRouteImport.update({
    id: '/scan-presensi',
    path: '/scan-presensi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absensi-diri': typeof AuthenticatedAbsensiDiriRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kesiswaan': typeof AuthenticatedKesiswaanRoute
  '/manajemen-asrama': typeof AuthenticatedManajemenAsramaRoute
  '/manajemen-halaqoh': typeof AuthenticatedManajemenHalaqohRoute
  '/manajemen-kelas': typeof AuthenticatedManajemenKelasRoute
  '/mutabaah-saya': typeof AuthenticatedMutabaahSayaRoute
  '/pelanggaran-saya': typeof AuthenticatedPelanggaranSayaRoute
  '/pengaturan-sesi': typeof AuthenticatedPengaturanSesiRoute
  '/presensi-insidental': typeof AuthenticatedPresensiInsidentalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rekap-presensi': typeof AuthenticatedRekapPresensiRoute
  '/scan-presensi': typeof AuthenticatedScanPresensiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absensi-diri': typeof AuthenticatedAbsensiDiriRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kesiswaan': typeof AuthenticatedKesiswaanRoute
  '/manajemen-asrama': typeof AuthenticatedManajemenAsramaRoute
  '/manajemen-halaqoh': typeof AuthenticatedManajemenHalaqohRoute
  '/manajemen-kelas': typeof AuthenticatedManajemenKelasRoute
  '/mutabaah-saya': typeof AuthenticatedMutabaahSayaRoute
  '/pelanggaran-saya': typeof AuthenticatedPelanggaranSayaRoute
  '/pengaturan-sesi': typeof AuthenticatedPengaturanSesiRoute
  '/presensi-insidental': typeof AuthenticatedPresensiInsidentalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rekap-presensi': typeof AuthenticatedRekapPresensiRoute
  '/scan-presensi': typeof AuthenticatedScanPresensiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/absensi-diri': typeof AuthenticatedAbsensiDiriRoute
  '/_authenticated/anggota': typeof AuthenticatedAnggotaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/kesiswaan': typeof AuthenticatedKesiswaanRoute
  '/_authenticated/manajemen-asrama': typeof AuthenticatedManajemenAsramaRoute
  '/_authenticated/manajemen-halaqoh': typeof AuthenticatedManajemenHalaqohRoute
  '/_authenticated/manajemen-kelas': typeof AuthenticatedManajemenKelasRoute
  '/_authenticated/mutabaah-saya': typeof AuthenticatedMutabaahSayaRoute
  '/_authenticated/pelanggaran-saya': typeof AuthenticatedPelanggaranSayaRoute
  '/_authenticated/pengaturan-sesi': typeof AuthenticatedPengaturanSesiRoute
  '/_authenticated/presensi-insidental': typeof AuthenticatedPresensiInsidentalRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rekap-presensi': typeof AuthenticatedRekapPresensiRoute
  '/_authenticated/scan-presensi': typeof AuthenticatedScanPresensiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absensi-diri'
    | '/anggota'
    | '/dashboard'
    | '/kalender'
    | '/kesiswaan'
    | '/manajemen-asrama'
    | '/manajemen-halaqoh'
    | '/manajemen-kelas'
    | '/mutabaah-saya'
    | '/pelanggaran-saya'
    | '/pengaturan-sesi'
    | '/presensi-insidental'
    | '/profil'
    | '/rekap-presensi'
    | '/scan-presensi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absensi-diri'
    | '/anggota'
    | '/dashboard'
    | '/kalender'
    | '/kesiswaan'
    | '/manajemen-asrama'
    | '/manajemen-halaqoh'
    | '/manajemen-kelas'
    | '/mutabaah-saya'
    | '/pelanggaran-saya'
    | '/pengaturan-sesi'
    | '/presensi-insidental'
    | '/profil'
    | '/rekap-presensi'
    | '/scan-presensi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/absensi-diri'
    | '/_authenticated/anggota'
    | '/_authenticated/dashboard'
    | '/_authenticated/kalender'
    | '/_authenticated/kesiswaan'
    | '/_authenticated/manajemen-asrama'
    | '/_authenticated/manajemen-halaqoh'
    | '/_authenticated/manajemen-kelas'
    | '/_authenticated/mutabaah-saya'
    | '/_authenticated/pelanggaran-saya'
    | '/_authenticated/pengaturan-sesi'
    | '/_authenticated/presensi-insidental'
    | '/_authenticated/profil'
    | '/_authenticated/rekap-presensi'
    | '/_authenticated/scan-presensi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/absensi-diri': {
      id: '/_authenticated/absensi-diri'
      path: '/absensi-diri'
      fullPath: '/absensi-diri'
      preLoaderRoute: typeof AuthenticatedAbsensiDiriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggota': {
      id: '/_authenticated/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AuthenticatedAnggotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kesiswaan': {
      id: '/_authenticated/kesiswaan'
      path: '/kesiswaan'
      fullPath: '/kesiswaan'
      preLoaderRoute: typeof AuthenticatedKesiswaanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manajemen-asrama': {
      id: '/_authenticated/manajemen-asrama'
      path: '/manajemen-asrama'
      fullPath: '/manajemen-asrama'
      preLoaderRoute: typeof AuthenticatedManajemenAsramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manajemen-halaqoh': {
      id: '/_authenticated/manajemen-halaqoh'
      path: '/manajemen-halaqoh'
      fullPath: '/manajemen-halaqoh'
      preLoaderRoute: typeof AuthenticatedManajemenHalaqohRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manajemen-kelas': {
      id: '/_authenticated/manajemen-kelas'
      path: '/manajemen-kelas'
      fullPath: '/manajemen-kelas'
      preLoaderRoute: typeof AuthenticatedManajemenKelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mutabaah-saya': {
      id: '/_authenticated/mutabaah-saya'
      path: '/mutabaah-saya'
      fullPath: '/mutabaah-saya'
      preLoaderRoute: typeof AuthenticatedMutabaahSayaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggaran-saya': {
      id: '/_authenticated/pelanggaran-saya'
      path: '/pelanggaran-saya'
      fullPath: '/pelanggaran-saya'
      preLoaderRoute: typeof AuthenticatedPelanggaranSayaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan-sesi': {
      id: '/_authenticated/pengaturan-sesi'
      path: '/pengaturan-sesi'
      fullPath: '/pengaturan-sesi'
      preLoaderRoute: typeof AuthenticatedPengaturanSesiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presensi-insidental': {
      id: '/_authenticated/presensi-insidental'
      path: '/presensi-insidental'
      fullPath: '/presensi-insidental'
      preLoaderRoute: typeof AuthenticatedPresensiInsidentalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap-presensi': {
      id: '/_authenticated/rekap-presensi'
      path: '/rekap-presensi'
      fullPath: '/rekap-presensi'
      preLoaderRoute: typeof AuthenticatedRekapPresensiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan-presensi': {
      id: '/_authenticated/scan-presensi'
      path: '/scan-presensi'
      fullPath: '/scan-presensi'
      preLoaderRoute: typeof AuthenticatedScanPresensiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbsensiDiriRoute: typeof AuthenticatedAbsensiDiriRoute
  AuthenticatedAnggotaRoute: typeof AuthenticatedAnggotaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedKesiswaanRoute: typeof AuthenticatedKesiswaanRoute
  AuthenticatedManajemenAsramaRoute: typeof AuthenticatedManajemenAsramaRoute
  AuthenticatedManajemenHalaqohRoute: typeof AuthenticatedManajemenHalaqohRoute
  AuthenticatedManajemenKelasRoute: typeof AuthenticatedManajemenKelasRoute
  AuthenticatedMutabaahSayaRoute: typeof AuthenticatedMutabaahSayaRoute
  AuthenticatedPelanggaranSayaRoute: typeof AuthenticatedPelanggaranSayaRoute
  AuthenticatedPengaturanSesiRoute: typeof AuthenticatedPengaturanSesiRoute
  AuthenticatedPresensiInsidentalRoute: typeof AuthenticatedPresensiInsidentalRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRekapPresensiRoute: typeof AuthenticatedRekapPresensiRoute
  AuthenticatedScanPresensiRoute: typeof AuthenticatedScanPresensiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbsensiDiriRoute: AuthenticatedAbsensiDiriRoute,
  AuthenticatedAnggotaRoute: AuthenticatedAnggotaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedKesiswaanRoute: AuthenticatedKesiswaanRoute,
  AuthenticatedManajemenAsramaRoute: AuthenticatedManajemenAsramaRoute,
  AuthenticatedManajemenHalaqohRoute: AuthenticatedManajemenHalaqohRoute,
  AuthenticatedManajemenKelasRoute: AuthenticatedManajemenKelasRoute,
  AuthenticatedMutabaahSayaRoute: AuthenticatedMutabaahSayaRoute,
  AuthenticatedPelanggaranSayaRoute: AuthenticatedPelanggaranSayaRoute,
  AuthenticatedPengaturanSesiRoute: AuthenticatedPengaturanSesiRoute,
  AuthenticatedPresensiInsidentalRoute: AuthenticatedPresensiInsidentalRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRekapPresensiRoute: AuthenticatedRekapPresensiRoute,
  AuthenticatedScanPresensiRoute: AuthenticatedScanPresensiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
